In [15]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


### Importing NumPy
NumPy is a powerful Python library used for numerical computing.  
It provides support for arrays, mathematical functions, and linear algebra operations.

In [16]:
import numpy as np

### Creating a 1D NumPy Array
We create a one-dimensional NumPy array containing integers from 1 to 20 and perform
basic statistical operations.

In [17]:
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### Statistical Operations
We calculate the sum, mean, median, and standard deviation of the array.

In [18]:
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))

Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398


### Finding Indices of Elements Greater Than 10
NumPy allows conditional indexing using `np.where()`.

In [19]:
indices = np.where(arr > 10)
indices

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int64),)

### Creating a 4 × 4 2D Array
We reshape numbers from 1 to 16 into a 4 × 4 matrix.

In [20]:
array_2d = np.arange(1, 17).reshape(4, 4)
array_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### Transpose of the Array
The transpose switches rows and columns.

In [21]:
array_2d.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

### Row-wise and Column-wise Sum
Axis = 1 → Row-wise  
Axis = 0 → Column-wise

In [22]:
print("Row-wise sum:", np.sum(array_2d, axis=1))
print("Column-wise sum:", np.sum(array_2d, axis=0))

Row-wise sum: [10 26 42 58]
Column-wise sum: [28 32 36 40]


### Random 3 × 3 Arrays
We create two random arrays and perform arithmetic and matrix multiplication.

In [23]:
a = np.random.randint(1, 21, (3, 3))
b = np.random.randint(1, 21, (3, 3))

a, b

(array([[12, 14,  3],
        [16, 13, 11],
        [11,  9, 14]]),
 array([[ 5,  6,  7],
        [12, 16, 13],
        [17, 13, 18]]))

In [24]:
print("Addition:\n", a + b)
print("Subtraction:\n", a - b)
print("Multiplication:\n", a * b)

Addition:
 [[17 20 10]
 [28 29 24]
 [28 22 32]]
Subtraction:
 [[ 7  8 -4]
 [ 4 -3 -2]
 [-6 -4 -4]]
Multiplication:
 [[ 60  84  21]
 [192 208 143]
 [187 117 252]]


In [25]:
np.dot(a, b)

array([[279, 335, 320],
       [423, 447, 479],
       [401, 392, 446]])

### Reshaping and Slicing
We reshape a 1D array of size 12 into a 3 × 4 array and slice:
- First two rows
- Last two columns

In [26]:
arr1d = np.arange(1, 13)
arr2d = arr1d.reshape(3, 4)

arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
arr2d[:2, -2:]

array([[3, 4],
       [7, 8]])